name: familiar_faces

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  auto_size_text: ^3.0.0
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  flutter_typeahead: ^4.7.0
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.1
  package_info_plus: ^4.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: false # this library is kind of a pain for android so just using android studio instead
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/